export const ACTION_TYPES_GENERAL = {
    ACTION_IS_LOADING: 'ACTION_IS_LOADING',
    ACTION_IS_NOTIFICATION: 'ACTION_IS_NOTIFICATION'
}

export const ACTION_TYPES_SESSION = {
    ACTION_GET_TOKEN: 'ACTION_GET_TOKEN',
    ACTION_LOG_OUT: 'ACTION_LOG_OUT'
}

export const ACTION_TYPES_ACCOUNT = {
    ACTION_LOGUT_ACCOUNT: 'ACTION_LOGOUT_ACCOUNT',
    ACTION_CREATE_NEW_ACCOUNT: 'ACTION_CREATE_NEW_ACCOUNT',
    ACTION_GET_ACCOUNT_INFO: 'ACTION_GET_ACCOUNT_INFO',
    ACTION_UPDATE_ACCOUNT_INFO: 'ACTION_UPDATE_ACCOUNT_INFO'
}

export const ACTION_TYPES_POST = {
    ACTION_GET_INFO_POST: 'ACTION_GET_INFO_POST',
    ACTION_CREATE_INFO_POST: 'ACTION_CREATE_INFO_POST',
    ACTION_GET_ALL_POSTS: 'ACTION_GET_ALL_POSTS',
    ACTION_UPDATE_INFO_POST: 'ACTION_UPDATE_INFO_POST' 
}
